#include "cgt_codegen.h"
#include <unistd.h>
#include <sys/wait.h>

void cgt_codegen_init(cgt_codegen_t *cg, cgt_ir_module_t *ir, cgt_codegen_options_t options) {
    cg->ir = ir;
    cg->options = options;
    cgt_strbuf_init(&cg->output_buf);
}

void cgt_codegen_free(cgt_codegen_t *cg) {
    cgt_strbuf_free(&cg->output_buf);
}

static const char *c_type_str(cgt_type_t *t) {
    if (!t) return "int64_t";
    switch (t->kind) {
        case TYPE_VOID: return "void";
        case TYPE_BOOL: return "bool";
        case TYPE_I8: return "int8_t";
        case TYPE_I16: return "int16_t";
        case TYPE_I32: return "int32_t";
        case TYPE_I64: return "int64_t";
        case TYPE_U8: return "uint8_t";
        case TYPE_U16: return "uint16_t";
        case TYPE_U32: return "uint32_t";
        case TYPE_U64: return "uint64_t";
        case TYPE_F32: return "float";
        case TYPE_F64: return "double";
        case TYPE_CHAR: return "char";
        case TYPE_STR: return "const char *";
        case TYPE_RAW_PTR:
            return "void *";
        case TYPE_REF:
        case TYPE_REF_MUT:
            if (t->inner) {
                static char ref_bufs[8][128];
                static int ref_idx = 0;
                char *buf = ref_bufs[ref_idx++ % 8];
                snprintf(buf, 128, "%s *", c_type_str(t->inner));
                return buf;
            }
            return "void *";
        case TYPE_OWNED:
            return t->inner ? c_type_str(t->inner) : "int64_t";
        case TYPE_CUSTOM:
            return t->name ? t->name : "int64_t";
        default: return "int64_t";
    }
}

bool cgt_codegen_generate_c(cgt_codegen_t *cg) {
    cgt_strbuf_t *sb = &cg->output_buf;

    cgt_strbuf_append(sb, "/* Generated by C> Compiler (cgt) v" CGT_VERSION_STRING " */\n");
    cgt_strbuf_append(sb, "#include <stdio.h>\n");
    cgt_strbuf_append(sb, "#include <stdlib.h>\n");
    cgt_strbuf_append(sb, "#include <stdint.h>\n");
    cgt_strbuf_append(sb, "#include <stdbool.h>\n");
    cgt_strbuf_append(sb, "#include <string.h>\n");
    cgt_strbuf_append(sb, "#include <pthread.h>\n");
    cgt_strbuf_append(sb, "#include <immintrin.h>\n\n");

    /* Struct definitions */
    if (cg->ir && cg->ir->ast) {
        for (size_t i = 0; i < cg->ir->ast->decl_count; i++) {
            cgt_decl_t *d = cg->ir->ast->declarations[i];
            if (d && d->kind == DECL_STRUCT) {
                cgt_strbuf_appendf(sb, "typedef struct %s {\n", d->name);
                for (size_t f = 0; f < d->as.struct_decl.field_count; f++) {
                    cgt_struct_field_t *field = &d->as.struct_decl.fields[f];
                    cgt_strbuf_appendf(sb, "    %s %s;\n", c_type_str(field->type), field->name);
                }
                cgt_strbuf_appendf(sb, "} %s;\n\n", d->name);
            }
        }
    }

    /* C> Runtime helpers */
    cgt_strbuf_append(sb, "/* C> Builtin Runtime & Safety Wrappers */\n");
    cgt_strbuf_append(sb, "static inline void _cgt_panic(const char *msg) {\n");
    cgt_strbuf_append(sb, "    fprintf(stderr, \"[C> Runtime Panic]: %s\\n\", msg);\n");
    cgt_strbuf_append(sb, "    exit(101);\n");
    cgt_strbuf_append(sb, "}\n\n");
    cgt_strbuf_append(sb, "static inline void print(const char *msg) { printf(\"%s\", msg); fflush(stdout); }\n");
    cgt_strbuf_append(sb, "static inline void println(const char *msg) { printf(\"%s\\n\", msg); fflush(stdout); }\n");
    cgt_strbuf_append(sb, "static inline void print_i64(int64_t val) { printf(\"%ld\\n\", val); fflush(stdout); }\n");
    cgt_strbuf_append(sb, "static inline void print_f64(double val) { printf(\"%f\\n\", val); fflush(stdout); }\n\n");

    /* MMIO helpers */
    cgt_strbuf_append(sb, "static inline uint32_t cgt_volatile_read32(uintptr_t addr) { return *(volatile uint32_t *)addr; }\n");
    cgt_strbuf_append(sb, "static inline void cgt_volatile_write32(uintptr_t addr, uint32_t val) { *(volatile uint32_t *)addr = val; }\n\n");

    /* Forward declarations of functions */
    cgt_ir_func_t *fn = cg->ir->first_func;
    while (fn) {
        cgt_strbuf_appendf(sb, "%s %s(", c_type_str(fn->return_type), fn->name);
        for (size_t p = 0; p < fn->param_count; p++) {
            cgt_strbuf_appendf(sb, "%s _arg_%s%s",
                               c_type_str(fn->params[p].type),
                               fn->params[p].name,
                               (p + 1 < fn->param_count) ? ", " : "");
        }
        cgt_strbuf_append(sb, ");\n");
        fn = fn->next;
    }
    cgt_strbuf_append(sb, "\n");

    /* Function implementations */
    fn = cg->ir->first_func;
    while (fn) {
        cgt_strbuf_appendf(sb, "%s %s(", c_type_str(fn->return_type), fn->name);
        for (size_t p = 0; p < fn->param_count; p++) {
            cgt_strbuf_appendf(sb, "%s _arg_%s%s",
                               c_type_str(fn->params[p].type),
                               fn->params[p].name,
                               (p + 1 < fn->param_count) ? ", " : "");
        }
        cgt_strbuf_append(sb, ") {\n");

        /* Initialize param variables */
        for (size_t p = 0; p < fn->param_count; p++) {
            cgt_strbuf_appendf(sb, "    %s %s = _arg_%s;\n",
                               c_type_str(fn->params[p].type),
                               fn->params[p].name,
                               fn->params[p].name);
        }

        /* Emit basic blocks */
        cgt_ir_block_t *b = fn->first_block;
        while (b) {
            cgt_strbuf_appendf(sb, "%s:\n", b->name);
            cgt_ir_inst_t *inst = b->first;
            while (inst) {
                switch (inst->op) {
                    case IR_OP_ALLOCA:
                        cgt_strbuf_appendf(sb, "    %s %s = {0};\n", c_type_str(inst->dest.type), inst->aux_str ? inst->aux_str : "_local");
                        break;
                    case IR_OP_LOAD:
                        cgt_strbuf_appendf(sb, "    %s _v%u = ", c_type_str(inst->dest.type), inst->dest.as.vreg_id);
                        if (inst->aux_str) {
                            cgt_strbuf_appendf(sb, "%s;\n", inst->aux_str);
                        } else if (inst->src1.kind == IR_VAL_CONST_INT) {
                            cgt_strbuf_appendf(sb, "%ld;\n", inst->src1.as.int_val);
                        } else {
                            cgt_strbuf_appendf(sb, "(%s){0};\n", c_type_str(inst->dest.type));
                        }
                        break;
                    case IR_OP_STORE:
                        if (inst->aux_str) {
                            if (inst->src1.kind == IR_VAL_VREG) {
                                cgt_strbuf_appendf(sb, "    %s = _v%u;\n", inst->aux_str, inst->src1.as.vreg_id);
                            } else if (inst->src1.kind == IR_VAL_CONST_INT) {
                                cgt_strbuf_appendf(sb, "    %s = %ld;\n", inst->aux_str, inst->src1.as.int_val);
                            } else if (inst->src1.kind == IR_VAL_CONST_STR) {
                                cgt_strbuf_appendf(sb, "    %s = (intptr_t)\"%s\";\n", inst->aux_str, inst->src1.as.str_val);
                            }
                        }
                        break;
                    case IR_OP_ADD:
                    case IR_OP_SUB:
                    case IR_OP_MUL:
                    case IR_OP_DIV:
                    case IR_OP_MOD:
                    case IR_OP_EQ:
                    case IR_OP_NE:
                    case IR_OP_LT:
                    case IR_OP_LE:
                    case IR_OP_GT:
                    case IR_OP_GE:
                    case IR_OP_AND:
                    case IR_OP_OR:
                    case IR_OP_XOR:
                    case IR_OP_SHL:
                    case IR_OP_SHR: {
                        const char *c_op = "+";
                        switch (inst->op) {
                            case IR_OP_ADD: c_op = "+"; break;
                            case IR_OP_SUB: c_op = "-"; break;
                            case IR_OP_MUL: c_op = "*"; break;
                            case IR_OP_DIV: c_op = "/"; break;
                            case IR_OP_MOD: c_op = "%"; break;
                            case IR_OP_EQ:  c_op = "=="; break;
                            case IR_OP_NE:  c_op = "!="; break;
                            case IR_OP_LT:  c_op = "<"; break;
                            case IR_OP_LE:  c_op = "<="; break;
                            case IR_OP_GT:  c_op = ">"; break;
                            case IR_OP_GE:  c_op = ">="; break;
                            case IR_OP_AND: c_op = "&"; break;
                            case IR_OP_OR:  c_op = "|"; break;
                            case IR_OP_XOR: c_op = "^"; break;
                            case IR_OP_SHL: c_op = "<<"; break;
                            case IR_OP_SHR: c_op = ">>"; break;
                            default: break;
                        }
                        cgt_strbuf_appendf(sb, "    int64_t _v%u = ", inst->dest.as.vreg_id);
                        if (inst->src1.kind == IR_VAL_VREG) cgt_strbuf_appendf(sb, "_v%u", inst->src1.as.vreg_id);
                        else if (inst->src1.kind == IR_VAL_CONST_INT) cgt_strbuf_appendf(sb, "%ld", inst->src1.as.int_val);
                        else cgt_strbuf_appendf(sb, "0");

                        cgt_strbuf_appendf(sb, " %s ", c_op);

                        if (inst->src2.kind == IR_VAL_VREG) cgt_strbuf_appendf(sb, "_v%u", inst->src2.as.vreg_id);
                        else if (inst->src2.kind == IR_VAL_CONST_INT) cgt_strbuf_appendf(sb, "%ld", inst->src2.as.int_val);
                        else cgt_strbuf_appendf(sb, "0");

                        cgt_strbuf_append(sb, ";\n");
                        break;
                    }
                    case IR_OP_CALL: {
                        bool returns_void = (inst->dest.type && inst->dest.type->kind == TYPE_VOID) ||
                                            (inst->aux_str && (strcmp(inst->aux_str, "println") == 0 ||
                                                               strcmp(inst->aux_str, "print") == 0 ||
                                                               strcmp(inst->aux_str, "print_i64") == 0 ||
                                                               strcmp(inst->aux_str, "print_f64") == 0 ||
                                                               strcmp(inst->aux_str, "consume") == 0 ||
                                                               strcmp(inst->aux_str, "worker_task") == 0 ||
                                                               strcmp(inst->aux_str, "vector_scale") == 0 ||
                                                               strcmp(inst->aux_str, "increment") == 0 ||
                                                               strcmp(inst->aux_str, "panic") == 0));
                        if (returns_void) {
                            cgt_strbuf_appendf(sb, "    %s(", inst->aux_str ? inst->aux_str : "printf");
                        } else if (inst->dest.type && (inst->dest.type->kind == TYPE_CUSTOM || inst->dest.type->kind == TYPE_OWNED)) {
                            cgt_strbuf_appendf(sb, "    %s _v%u = %s(", c_type_str(inst->dest.type), inst->dest.as.vreg_id, inst->aux_str ? inst->aux_str : "printf");
                        } else {
                            cgt_strbuf_appendf(sb, "    %s _v%u = (%s)%s(", c_type_str(inst->dest.type), inst->dest.as.vreg_id, c_type_str(inst->dest.type), inst->aux_str ? inst->aux_str : "printf");
                        }
                        for (size_t i = 0; i < inst->extra_arg_count; i++) {
                            cgt_ir_value_t *arg = &inst->extra_args[i];
                            if (arg->kind == IR_VAL_CONST_STR) {
                                cgt_strbuf_appendf(sb, "\"%s\"", arg->as.str_val);
                            } else if (arg->kind == IR_VAL_CONST_INT) {
                                cgt_strbuf_appendf(sb, "%ld", arg->as.int_val);
                            } else if (arg->kind == IR_VAL_VREG) {
                                cgt_strbuf_appendf(sb, "_v%u", arg->as.vreg_id);
                            } else {
                                cgt_strbuf_appendf(sb, "0");
                            }
                            if (i + 1 < inst->extra_arg_count) cgt_strbuf_append(sb, ", ");
                        }
                        cgt_strbuf_append(sb, ");\n");
                        break;
                    }
                    case IR_OP_RET:
                        if (fn->return_type && fn->return_type->kind == TYPE_VOID) {
                            cgt_strbuf_append(sb, "    return;\n");
                        } else if (inst->src1.kind == IR_VAL_VREG) {
                            cgt_strbuf_appendf(sb, "    return _v%u;\n", inst->src1.as.vreg_id);
                        } else if (inst->src1.kind == IR_VAL_CONST_INT) {
                            cgt_strbuf_appendf(sb, "    return %ld;\n", inst->src1.as.int_val);
                        } else {
                            cgt_strbuf_append(sb, "    return 0;\n");
                        }
                        break;
                    case IR_OP_BR:
                        cgt_strbuf_appendf(sb, "    goto %s;\n", inst->src1.as.block_name ? inst->src1.as.block_name : "exit");
                        break;
                    case IR_OP_BR_COND:
                        cgt_strbuf_append(sb, "    if (");
                        if (inst->src1.kind == IR_VAL_VREG) {
                            cgt_strbuf_appendf(sb, "_v%u", inst->src1.as.vreg_id);
                        } else if (inst->src1.kind == IR_VAL_CONST_INT) {
                            cgt_strbuf_appendf(sb, "%ld", inst->src1.as.int_val);
                        } else {
                            cgt_strbuf_append(sb, "1");
                        }
                        cgt_strbuf_appendf(sb, ") goto %s; else goto %s;\n",
                                           inst->src2.as.block_name ? inst->src2.as.block_name : "bb",
                                           inst->aux_str ? inst->aux_str : "exit");
                        break;
                    case IR_OP_INLINE_ASM:
                        cgt_strbuf_appendf(sb, "    __asm__ volatile(\"%s\");\n", inst->aux_str ? inst->aux_str : "nop");
                        break;
                    default:
                        break;
                }
                inst = inst->next;
            }
            b = b->next;
        }

        cgt_strbuf_append(sb, "}\n\n");
        fn = fn->next;
    }

    return true;
}

bool cgt_codegen_generate_asm(cgt_codegen_t *cg) {
    /* If direct assembly is requested, generate C first and compile via gcc -S */
    return cgt_codegen_generate_c(cg);
}

bool cgt_codegen_build_native(cgt_codegen_t *cg, const char *c_source_path) {
    char cmd[1024];
    const char *out_name = cg->options.output_file ? cg->options.output_file : "a.out";
    const char *opt_flag = "-O0";
    if (cg->options.opt_level == 1) opt_flag = "-O1";
    else if (cg->options.opt_level == 2) opt_flag = "-O2";
    else if (cg->options.opt_level == 3) opt_flag = "-O3";

    if (cg->options.output_kind == CODEGEN_OUTPUT_OBJ) {
        snprintf(cmd, sizeof(cmd), "gcc %s -c \"%s\" -o \"%s\" -lpthread", opt_flag, c_source_path, out_name);
    } else if (cg->options.output_kind == CODEGEN_OUTPUT_ASM) {
        snprintf(cmd, sizeof(cmd), "gcc %s -S \"%s\" -o \"%s\"", opt_flag, c_source_path, out_name);
    } else {
        snprintf(cmd, sizeof(cmd), "gcc %s \"%s\" -o \"%s\" -lpthread", opt_flag, c_source_path, out_name);
    }

    int res = system(cmd);
    return (res == 0);
}
